### ISSUE TITLE
verify dumonts group

### ISSUE THREAD

**Issue by vmatare** [clojars/administration#170]
I am requesting verification of an existing group. The group name is: dumonts

- [x] This group is based on a ~~GitHub or~~ GitLab organization (https://gitlab.com/dumonts)
- [x] I have created a public repository under that group named `clojars-vmatare` (https://gitlab.com/dumonts/clojars-vmatare)

**Comment by tobias** [comment]
Hi @vmatare - this verification will verify the groups `com.gitlab.dumonts` and `io.gitlab.dumonts`, is that what you are requesting? 

The existing `dumonts` group can't be verified, since it isn't reverse-domain-based. However, that only impacts releases for _new_projects; you can continue to release new versions of _existing_ projects that are in the `dumonts` group. Please see the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq) for more details.

**Comment by vmatare** [comment]
Thanks for the clarification @tobias. I wanted to publish a new project under the `dumonts` group, but you're saying that effectively no new projects can be published under that group (i.e. I can only update existing ones)?

If that's so then I can live with that and simply move to `com.gitlab.dumonts` or `io.gitlab.dumonts`. So go ahead with that verification, deprecating unqualified names like `dumonts` kinda makes sense to me ;-)

**Comment by tobias** [comment]
Correct, no new projects can be published under the `dumonts` group, since it can't be verified. 

The groups https://clojars.org/groups/com.gitlab.dumonts and https://clojars.org/groups/io.gitlab.dumonts  have been verified and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like, and feel free to use either group for new projects.
