### ISSUE TITLE
Group verification for `site.fabricate`

### ISSUE THREAD

**Issue by respatialized** [clojars/administration#219]
I am requesting verification of a new group for two users - the [`fabricate-site` organization](https://github.com/fabricate-site/) and myself. The group name is: `site.fabricate`.

- [x] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have added two TXT DNS records for the domain that have values of `clojars fabricate-site` & `clojars respatialized`.

`$ dig +short fabricate.site TXT`
```
"clojars fabricate-site"
"clojars respatialized"
```

Thanks in advance! 🙏🏻

**Comment by tobias** [comment]
The group https://clojars.org/groups/site.fabricate has been verified and you should now see the "verified" badge when you view it on your Clojars dashboard when logged in. You can delete the TXT record if you like.

I just added the Clojars user `respatialized` as a member of the group, since no user named `fabricate-site` exists on Clojars. If you do want another user account to access it, you can create that account then add it to the group via the Clojars UI.
