### ISSUE TITLE
Verification Request for io.gitlab.canterville group

### ISSUE THREAD

**Issue by ngrunwald** [clojars/administration#292]
I am requesting verification of a new group. The group name is: canterville

- [x] I have read the [FAQ](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] This group is based on a GitHub or GitLab organization, and I want to verify a reverse-domain-based group based on that organization ( https://gitlab.com/canterville -> `io.gitlab.canterville`)

**Comment by tobias** [comment]
Hi @ngrunwald! Are you trying to verify `canterville` as a group name, or `io.gitlab.canterville`? We can't verify `canterville` as a group name, since it isn't domain-based. But we can certainly verify `io.gitlab.canterville`; you just need to create a public repository under https://gitlab.com/canterville/clojars-<your_clojars_username>.

**Comment by ngrunwald** [comment]
Thanks, yes I was going for `io.gitlab.canterville`! repo is created here: https://gitlab.com/canterville/clojars-ngrunwald

**Comment by tobias** [comment]
Great! 

The groups com.gitlab.canterville & io.gitlab.canterville have been verified (you get both) and you should now see the "verified" badge when you view them on your Clojars dashboard when logged in. You can delete the verification repo if you like.

**Comment by ngrunwald** [comment]
Thanks a lot, and impressed by the speed!

**Comment by tobias** [comment]
My pleasure!
