### ISSUE TITLE
Allow one to own one's own name

### ISSUE THREAD

**Issue by piotr-yuxuan** [clojars/administration#33]
Hello :-)

Thank you so much for maintaining this piece of infrastructure!

In light of recent changes regarding https://github.com/clojars/clojars-web/wiki/Verified-Group-Names, my Clojars user `piotr-yuxuan` is now left with a group `piotr-yuxuan` (the exact same string) which is not verified. Would you consider to verify existing groups with the same name to account for cross-platform identities?

https://clojars.org/groups/piotr-yuxuan

This is more a general inquiry than actually a request, as I will comply with the new group naming strategy. My apologies if this question has already been asked, and replied.

**Comment by tobias** [comment]
Hi @piotr-yuxuan! Thanks for bringing this up. 

When coming up for a plan for verified group names, we considered having a way to verify existing non-reverse domain groups, but rejected it because it would require making exceptions for some group names and not others, and we were concerned about the ambiguity. So we decided on a firm, domain-name based policy since those would be globally unique (you can see that discussion [here](https://github.com/clojars/clojars-web/discussions/777#discussioncomment-396065)). I realize it is unlikely that someone would have `piotr-yuxuan` on multiple services, but we have to account for the case where one user may have github.com/foo, while another may have gitlab.com/foo, and they both want to claim the `foo` group. 

I do understand your position though, and that the new policy will require changes to some people's processes.

Note that you don't have to redeploy any _existing_ projects to a verified name (but can if you like) since future versions of existing projects can always be deployed. You only need a verified group name to deploy _new_ projects, just in case that wasn't clear.
