### ISSUE TITLE
org.clj-commons/pretty 1.0

### ISSUE THREAD

**Issue by hlship** [clojars/administration#338]
I am requesting deletion of my JAR because:

- [ ] There is a security vulnerability in a published JAR, i.e. malicious code
- [ ] Private credentials or code have been published.

If you are not requesting deletion for either of those reasons, we will not delete your artifact.

Artifact URL: https://clojars.org/org.clj-commons/pretty

This actually contains code for org.clj-commons/humanize, due to a cut-and-paste error.  The file is only minutes old, but this is confusing clj-doc, which is trying to build doc for pretty 1.0, which doesn't exist.

**Comment by tobias** [comment]
@hlship Normally we wouldn't delete an artifact for this case, but I decided to do so because the 1.0 version was showing as the latest/primary version on clojars instead of 2.0 since we sort by release date there. 1.0 will still be in various caches for a bit, but is no longer referenced on clojars.org.
