### ISSUE TITLE
Request for deletion of jar published

### ISSUE THREAD

**Issue by Charan2142** [clojars/administration#344]
I am requesting deletion of my JAR because:

Private credentials or code have been published.

If you are not requesting deletion for either of those reasons, we will not delete your artifact.

Artifact URL: https://clojars.org/org.clojars.tcreddy2142/trunova-datapipeline-utils/versions/0.1.0-SNAPSHOT

**Comment by tobias** [comment]
Hi @Charan2142, I can handle this for you. Can you push another release of the jar with a description of "Delete me" instead of "TruNova Data Pipeline Utils Library" to prove ownership? Let me know when that is done and I can delete it.

Also be aware that any credentials that may be in the jar should be considered compromised, and should be rotated ASAP.

**Comment by Charan2142** [comment]
Hi @tobias , I updated the description of the jar with "Delete Me". Can you please check and delete the jar?

**Comment by tobias** [comment]
Thanks @Charan2142. The jar has been deleted.
