### ISSUE TITLE
Verifying the Exoscale group

### ISSUE THREAD

**Issue by pyr** [clojars/administration#59]
Hi!

I know this is not supposed to be supported, but I thought I'd ask anyway. 
We've been deploying a number of artifacts under the **exoscale** group name for a while and we would love to have the ability
to keep it around to avoid migrating all our public artifacts to the new name scheme.

Since Exoscale is a registered trademark of the company, is there any chance we might have authorization to keep it?
I'm fine with going with the DNS TXT validation on exoscale.com or exoscale.ch to prove our identity anyhow, do you think this could work for you?

I am requesting verification of an existing group. The group name is: **exoscale**.

- [ ] This group is a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [ ] I have added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

**Comment by tobias** [comment]
Hi @pyr, thanks for getting in touch!

When coming up for a plan for verified group names, we considered having a way to verify existing non-reverse domain groups, but rejected it because it would require making exceptions for some group names and not others, and we were concerned about the ambiguity. So we decided on a firm, domain-name based policy since those would be globally unique (you can see that discussion [here](https://github.com/clojars/clojars-web/discussions/777#discussioncomment-396065)).

I do understand your position though, and that the new policy will require changes to some people's processes.

Note that you don't have to redeploy any _existing_ projects to a verified name since future versions of existing projects can always be deployed. You only need a verified group name to deploy _new_ projects, just in case that wasn't clear.

There is an [ongoing discussion](https://github.com/clojars/clojars-web/issues/801) around supporting Maven's group relocation facility, but it's currently unknown what we will do there.

**Comment by plexus** [comment]
Hey @pyr , please do weigh in on the [relaction issue](https://github.com/clojars/clojars-web/issues/801) if you think that would be valuable for Exoscale.
