### ISSUE TITLE
fourtytoo

### ISSUE THREAD

**Issue by fourtytoo** [clojars/administration#80]
I am requesting verification of a existing group. The group name is: fourtytoo

- [x] This group is not a [reverse-domain-based group](https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#faq)
- [x] I have not added a TXT DNS record for the domain that has a value of `clojars <your clojars username>`

The group name comes simply from my github account.  No domain name.
To keep using this group do I need to rename it to net.clojars.fourtytoo? org.clojars.fourtytoo?  Do I need to change all my project.clj files to match such change?

Thanks in advance

**Comment by tobias** [comment]
Hi @fourtytoo!

We aren't verifying non-reverse-domain-based groups, since they aren't unique. However, you can continue to deploy versions of existing projects to the group `fourtytoo` forever - you just can't deploy _new_ projects to it.

For new projects, you have several choices in addition to using your own domain name; see this section of the wiki: https://github.com/clojars/clojars-web/wiki/Verified-Group-Names#do-i-have-to-have-my-own-domain-name-to-publish-to-clojars

Please reopen this issue if that needs more clarification.
